/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package control.de.notas.raul;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author A21-PC27
 */
public class PanelNota extends javax.swing.JFrame {

    /**
     * Creates new form PanelNota
     */
    public PanelNota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNombre = new javax.swing.JLabel();
        lbMateria = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        cbMateria5 = new javax.swing.JComboBox<>();
        cbMateria6 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lbControlDeNotas = new javax.swing.JLabel();
        lbNOMBRES1 = new javax.swing.JLabel();
        lbCARRERA = new javax.swing.JLabel();
        lbCICLO = new javax.swing.JLabel();
        lbCUM = new javax.swing.JLabel();
        lbMATERIAS1 = new javax.swing.JLabel();
        lbUV = new javax.swing.JLabel();
        lbNOTA = new javax.swing.JLabel();
        cbMATERIA1 = new javax.swing.JComboBox<>();
        cbMATERIA2 = new javax.swing.JComboBox<>();
        cbMATERIA3 = new javax.swing.JComboBox<>();
        cbMATERIA4 = new javax.swing.JComboBox<>();
        cbMATERIA5 = new javax.swing.JComboBox<>();
        cbUV1 = new javax.swing.JComboBox<>();
        cbUV2 = new javax.swing.JComboBox<>();
        cbUV3 = new javax.swing.JComboBox<>();
        cbUV4 = new javax.swing.JComboBox<>();
        cbUV5 = new javax.swing.JComboBox<>();
        tfNOTA1 = new javax.swing.JTextField();
        tfNOTA2 = new javax.swing.JTextField();
        tfNOTA3 = new javax.swing.JTextField();
        tfNOTA4 = new javax.swing.JTextField();
        tfNOTA5 = new javax.swing.JTextField();
        lbESTADO1 = new javax.swing.JLabel();
        lbESTADO2 = new javax.swing.JLabel();
        lbESTADO3 = new javax.swing.JLabel();
        lbESTADO4 = new javax.swing.JLabel();
        lbESTADO5 = new javax.swing.JLabel();
        tfNOMBRE1 = new javax.swing.JTextField();
        cbCARRERA = new javax.swing.JComboBox<>();
        cbCICLO = new javax.swing.JComboBox<>();
        tfCUM = new javax.swing.JTextField();
        btCALCULAR = new javax.swing.JButton();
        lbAVISOMENSAJE = new javax.swing.JTextField();

        lbNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNombre.setText("NOMBRE");

        lbMateria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMateria.setText("MATERIA");

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        cbMateria5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        cbMateria6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        lbControlDeNotas.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        lbControlDeNotas.setText("CONTROL DE NOTAS");

        lbNOMBRES1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNOMBRES1.setText("NOMBRE");

        lbCARRERA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCARRERA.setText("CARRERA");

        lbCICLO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCICLO.setText("CICLO");

        lbCUM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbCUM.setText("CUM");

        lbMATERIAS1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMATERIAS1.setText("MATERIA");

        lbUV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUV.setText("UV");

        lbNOTA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNOTA.setText("NOTA");

        cbMATERIA1.setFont(new java.awt.Font("SketchFlow Print", 0, 12)); // NOI18N
        cbMATERIA1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        cbMATERIA2.setFont(new java.awt.Font("SketchFlow Print", 0, 12)); // NOI18N
        cbMATERIA2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        cbMATERIA3.setFont(new java.awt.Font("SketchFlow Print", 0, 12)); // NOI18N
        cbMATERIA3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        cbMATERIA4.setFont(new java.awt.Font("SketchFlow Print", 0, 12)); // NOI18N
        cbMATERIA4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        cbMATERIA5.setFont(new java.awt.Font("SketchFlow Print", 0, 12)); // NOI18N
        cbMATERIA5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "Investigación de Operaciones I", "Electronica", "Legislación Aplicada a la Empresa", "Desarro de Software I", "Base de Datos II" }));

        cbUV1.setFont(new java.awt.Font("SketchFlow Print", 0, 12)); // NOI18N
        cbUV1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUV1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbUV2.setFont(new java.awt.Font("SketchFlow Print", 0, 12)); // NOI18N
        cbUV2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUV2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbUV3.setFont(new java.awt.Font("SketchFlow Print", 0, 12)); // NOI18N
        cbUV3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUV3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbUV4.setFont(new java.awt.Font("SketchFlow Print", 0, 12)); // NOI18N
        cbUV4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUV4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbUV5.setFont(new java.awt.Font("SketchFlow Print", 0, 12)); // NOI18N
        cbUV5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Opciones --", "3", "4" }));
        cbUV5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tfNOTA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNOTA1ActionPerformed(evt);
            }
        });

        tfNOTA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNOTA2ActionPerformed(evt);
            }
        });

        tfNOTA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNOTA3ActionPerformed(evt);
            }
        });

        tfNOTA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNOTA4ActionPerformed(evt);
            }
        });

        tfNOTA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNOTA5ActionPerformed(evt);
            }
        });

        lbESTADO1.setFont(new java.awt.Font("SketchFlow Print", 1, 14)); // NOI18N
        lbESTADO1.setForeground(new java.awt.Color(255, 255, 255));
        lbESTADO1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbESTADO1.setText("Estado");

        lbESTADO2.setFont(new java.awt.Font("SketchFlow Print", 1, 14)); // NOI18N
        lbESTADO2.setForeground(new java.awt.Color(255, 255, 255));
        lbESTADO2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbESTADO2.setText("Estado");

        lbESTADO3.setFont(new java.awt.Font("SketchFlow Print", 1, 14)); // NOI18N
        lbESTADO3.setForeground(new java.awt.Color(255, 255, 255));
        lbESTADO3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbESTADO3.setText("Estado");

        lbESTADO4.setFont(new java.awt.Font("SketchFlow Print", 1, 14)); // NOI18N
        lbESTADO4.setForeground(new java.awt.Color(255, 255, 255));
        lbESTADO4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbESTADO4.setText("Estado");

        lbESTADO5.setFont(new java.awt.Font("SketchFlow Print", 1, 14)); // NOI18N
        lbESTADO5.setForeground(new java.awt.Color(255, 255, 255));
        lbESTADO5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbESTADO5.setText("Estado");

        tfNOMBRE1.setFont(new java.awt.Font("SketchFlow Print", 0, 12)); // NOI18N
        tfNOMBRE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNOMBRE1ActionPerformed(evt);
            }
        });

        cbCARRERA.setFont(new java.awt.Font("SketchFlow Print", 0, 12)); // NOI18N
        cbCARRERA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccion --", "Ingenieria Industrial", "Ingenieria en Sistemas", "Ingenieria Electrica", "Ingenieria en Agronegocios" }));

        cbCICLO.setFont(new java.awt.Font("SketchFlow Print", 0, 12)); // NOI18N
        cbCICLO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccion --", "Ciclo 01", "Ciclo 02", " " }));

        tfCUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCUMActionPerformed(evt);
            }
        });

        btCALCULAR.setFont(new java.awt.Font("SketchFlow Print", 0, 14)); // NOI18N
        btCALCULAR.setText("CALCULAR");
        btCALCULAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCALCULARActionPerformed(evt);
            }
        });

        lbAVISOMENSAJE.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        lbAVISOMENSAJE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbAVISOMENSAJEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(lbControlDeNotas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btCALCULAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNOMBRE1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNOMBRES1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbCARRERA, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbCICLO, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbCARRERA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbCICLO)
                                        .addGap(81, 81, 81)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(tfCUM, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbCUM)
                                        .addGap(22, 22, 22))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbMATERIAS1)
                                .addGap(162, 162, 162)
                                .addComponent(lbUV)
                                .addGap(113, 113, 113)
                                .addComponent(lbNOTA))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMATERIA1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMATERIA2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMATERIA3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMATERIA4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMATERIA5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbUV1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUV2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUV3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUV4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbUV5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfNOTA1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(lbESTADO1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfNOTA2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(lbESTADO2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNOTA3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNOTA4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfNOTA5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbESTADO4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbESTADO3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbESTADO5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(lbAVISOMENSAJE, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbControlDeNotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbNOMBRES1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNOMBRE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCARRERA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCICLO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCARRERA)
                            .addComponent(lbCICLO)
                            .addComponent(lbCUM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfCUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMATERIAS1)
                            .addComponent(lbUV)
                            .addComponent(lbNOTA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMATERIA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMATERIA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNOTA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMATERIA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNOTA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMATERIA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNOTA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbESTADO4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbMATERIA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbUV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNOTA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbESTADO5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNOTA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbESTADO1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbESTADO2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbESTADO3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAVISOMENSAJE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCALCULAR))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNOTA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNOTA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNOTA1ActionPerformed

    private void tfNOTA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNOTA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNOTA2ActionPerformed

    private void tfNOTA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNOTA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNOTA3ActionPerformed

    private void tfNOTA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNOTA4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNOTA4ActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfNOMBRE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNOMBRE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNOMBRE1ActionPerformed

    private void btCALCULARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCALCULARActionPerformed
        // TODO add your handling code here:
        String carrera = "";
        String ciclo = "";
        String nota = "";
        int uv1,uv2,uv3,uv4,uv5;
        int reprobado=0,aprobado=0;
        float cum;
        float nota1,nota2,nota3,nota4,nota5;
        
        String carreraSeleccionada = (String) cbCARRERA.getSelectedItem();
        String cicloSeleccionado = (String) cbCICLO.getSelectedItem();
        String materia1 = (String) cbMATERIA1.getSelectedItem();
        String materia2 = (String) cbMATERIA2.getSelectedItem();
        String materia3 = (String) cbMATERIA3.getSelectedItem();
        String materia4 = (String) cbMATERIA4.getSelectedItem();
        String materia5 = (String) cbMateria5.getSelectedItem();
        String num1 = tfNOTA1.getText();
        String num2 = tfNOTA2.getText();
        String num3 = tfNOTA3.getText();
        String num4 = tfNOTA4.getText();
        String num5 = tfNOTA5.getText();
        String nombre = tfNOMBRE1.getText();
        String UVmateria1 = (String) cbUV1.getSelectedItem();
        String UVmateria2 = (String) cbUV2.getSelectedItem();
        String UVmateria3 = (String) cbUV3.getSelectedItem();
        String UVmateria4 = (String) cbUV4.getSelectedItem();
        String UVmateria5 = (String) cbUV5.getSelectedItem();
       
        // Llenar los campos que se piden
        if("Elegir una opción".equals(carreraSeleccionada) || "Elegir una opción".equals(cicloSeleccionado) 
                ||"Elegir una opción".equals(materia1) || "Elegir una opción".equals(materia2) || "Elegir una opción".equals(materia3)
                || "Elegir una opción".equals(materia4) || "Elegir una opción".equals(materia5) || "Elegir una opción".equals(UVmateria1)
                || "Elegir una opción".equals(UVmateria2) || "Elegir una opción".equals(UVmateria3) || "Elegir una opción".equals(UVmateria4)
                || "Elegir una opción".equals(UVmateria5) ||num1.isEmpty() || num2.isEmpty() || num3.isEmpty() || num4.isEmpty() || num5.isEmpty() || nombre.isEmpty()) {
            carrera = "-1";
            ciclo = "-1";
            
            JOptionPane.showMessageDialog(this, "Llene todos los campos solicitados.", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
        // Convertir string a int y a float con un parseo
        nota1 = Float.parseFloat(num1); 
        nota2 = Float.parseFloat(num2); 
        nota3 = Float.parseFloat(num3); 
        nota4 = Float.parseFloat(num4); 
        nota5 = Float.parseFloat(num5); 
        uv1 = Integer.parseInt(UVmateria1);
        uv2 = Integer.parseInt(UVmateria2);
        uv3 = Integer.parseInt(UVmateria3);
        uv4 = Integer.parseInt(UVmateria4);
        uv5 = Integer.parseInt(UVmateria5);
        
        
        //Validar que las notas sean mayores a 0 y menores a 10
        if(!(nota1 <= 10) || !(nota1 >= 0) || !(nota2 <= 10) || !(nota2 >= 0) || !(nota3 <= 10) || !(nota3 >= 0) || !(nota4 <= 10) || !(nota4 >= 0)
                || !(nota5 <= 10) || !(nota5 >= 0)){
           nota = "-1";
           JOptionPane.showMessageDialog(this, "Ingrese un dato válido en notas.", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
        // Mostrar Resultado 
        if(!"-1".equals(carrera) && !"-1".equals(ciclo) && !"-1".equals(nota)){
            
            //Le quitamos lo transparente que tiene por defecto a JLabel.
            lbESTADO1.setOpaque(true);
            lbESTADO2.setOpaque(true);
            lbESTADO3.setOpaque(true);
            lbESTADO4.setOpaque(true);
            lbESTADO5.setOpaque(true);
            
             // Cambiar estado a Reprobado o Aprobado
        if(nota1 < 6){
            lbESTADO1.setText("Reprobado");
            lbESTADO1.setBackground(Color.orange);
            reprobado++;
        }else{
            lbESTADO1.setText("Aprobado");
            lbESTADO1.setBackground(Color.blue);
            aprobado++;
        }
        if(nota2 < 6){
            lbESTADO2.setText("Reprobado");
            lbESTADO2.setBackground(Color.orange);
            reprobado++;
        }else{
            lbESTADO2.setText("Aprobado");
            lbESTADO2.setBackground(Color.blue);
            aprobado++;
        }
        if(nota3 < 6){
            lbESTADO3.setText("Reprobado");
            lbESTADO3.setBackground(Color.orange);
            reprobado++;
        }else{
            lbESTADO3.setText("Aprobado");
            lbESTADO3.setBackground(Color.blue);
            aprobado++;
        }
        if(nota4 < 6){
            lbESTADO4.setText("Reprobado");
            lbESTADO4.setBackground(Color.orange);
            reprobado++;
        }else{
            lbESTADO4.setText("Aprobado");
            lbESTADO4.setBackground(Color.blue);
            aprobado++;
        }
        if(nota5 < 6){
            lbESTADO5.setText("Reprobado");
            lbESTADO5.setBackground(Color.orange);
            reprobado++;
        }else{
            lbESTADO5.setText("Aprobado");
            lbESTADO5.setBackground(Color.blue);
            aprobado++;
        }
        
        //Cálculo del CUM
        cum = ((nota1*uv1)+(nota2*uv2)+(nota3*uv3)+(nota4*uv4)+(nota5*uv5))/(uv1+uv2+uv3+uv4+uv5);
        
        // Convertir double e int a string
        String TotalCum = Float.toString(cum);
        String MateriasAprobadas = Integer.toString(aprobado);
        String MateriasReprobadas = Integer.toString(reprobado);
        
            tfCUM.setText(TotalCum);
            
            lbAVISOMENSAJE.setText(this.tfNombre.getText()
                + " su estado actual es de "
                + MateriasAprobadas 
                 + "\n"   
                + " materias aprobadas y "
                + MateriasReprobadas
                 +"\n" 
                + " reprobadas y su CUM actual es de "
                + this.tfCUM.getText());
        }
    }//GEN-LAST:event_btCALCULARActionPerformed

    private void tfCUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCUMActionPerformed

    private void tfNOTA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNOTA5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNOTA5ActionPerformed

    private void lbAVISOMENSAJEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbAVISOMENSAJEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbAVISOMENSAJEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCALCULAR;
    private javax.swing.JComboBox<String> cbCARRERA;
    private javax.swing.JComboBox<String> cbCICLO;
    private javax.swing.JComboBox<String> cbMATERIA1;
    private javax.swing.JComboBox<String> cbMATERIA2;
    private javax.swing.JComboBox<String> cbMATERIA3;
    private javax.swing.JComboBox<String> cbMATERIA4;
    private javax.swing.JComboBox<String> cbMATERIA5;
    private javax.swing.JComboBox<String> cbMateria5;
    private javax.swing.JComboBox<String> cbMateria6;
    private javax.swing.JComboBox<String> cbUV1;
    private javax.swing.JComboBox<String> cbUV2;
    private javax.swing.JComboBox<String> cbUV3;
    private javax.swing.JComboBox<String> cbUV4;
    private javax.swing.JComboBox<String> cbUV5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lbAVISOMENSAJE;
    private javax.swing.JLabel lbCARRERA;
    private javax.swing.JLabel lbCICLO;
    private javax.swing.JLabel lbCUM;
    private javax.swing.JLabel lbControlDeNotas;
    private javax.swing.JLabel lbESTADO1;
    private javax.swing.JLabel lbESTADO2;
    private javax.swing.JLabel lbESTADO3;
    private javax.swing.JLabel lbESTADO4;
    private javax.swing.JLabel lbESTADO5;
    private javax.swing.JLabel lbMATERIAS1;
    private javax.swing.JLabel lbMateria;
    private javax.swing.JLabel lbNOMBRES1;
    private javax.swing.JLabel lbNOTA;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbUV;
    private javax.swing.JTextField tfCUM;
    private javax.swing.JTextField tfNOMBRE1;
    private javax.swing.JTextField tfNOTA1;
    private javax.swing.JTextField tfNOTA2;
    private javax.swing.JTextField tfNOTA3;
    private javax.swing.JTextField tfNOTA4;
    private javax.swing.JTextField tfNOTA5;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
